# Generated by Django 4.1.3 on 2022-11-26 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_desc_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
    ]
